@echo off
echo Starting Express backend...
start cmd /k "cd backend && npm run dev:server"

echo Starting Vite frontend...
start cmd /k "cd frontend && npm run dev"

echo Both frontend and backend are launching...
